version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    expose:
      - 5672
      - 15672
    networks:
      - net
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:15
    hostname: postgres
    expose:
      - 5432
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      FORCE_SSL: TRUE
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:4
    hostname: adminer
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://adminer:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  net:
