version: '3'

services:
  server-auth:
    image: zhoooot/server-admin:s1.1.0
    restart: on-failure
    networks:
      - net
      - admin-net
    env_file:
      - ./.server-admin.env
    ports:
      - 4006:4006
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

networks:
  net:
  admin-net:
