version: '3'

services:
  server-auth:
    image: zhoooot/server-auth:s1.0.0
    restart: on-failure
    networks:
      - net
      - auth-net
    env_file:
      - ./.server-auth.env
    ports:
      - 4006:4006
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis-server-auth:
        condition: service_healthy
  redis-server-auth:
    hostname: redis-server-auth
    image: redis:5.0.5-alpine
    networks:
      - auth-net
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  net:
  auth-net:
