version: "3"

services:
  server-creator:
    image: zhoooot/server-quiz:1.0.0
    restart: on-failure
    ports:
      - 4000:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    hostname: db
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server_creator
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
