version: "3"

services:
  server-creator:
    image: zhoooot/server-creator:1.0.0
    restart: on-failure
    ports:
      - 4003:3001
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    hostname: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server_creator
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10
